Repository TeamShortWeather/ShortWeather-iOS, pull requests merged in 2023-01, with the labels that each got.

#12 Feature/#5 today weather2
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/CellType.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/CollectionViewCell/HourCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/CommuteTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/View/SecondTodayWeatherView.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/ViewController/TestViewController.swift
  ShortWeather/ShortWeather/Util/Extension/UIButton+.swift
Labels: Design, 🐰민

#10 Feature/#4 - BaseLocationViewController 완성, TodayWeatherViewController 생성
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Presentation/Common/Base/View/LocationView.swift
  ShortWeather/ShortWeather/Presentation/Common/Base/ViewController/BaseLocationViewController.swift
  ShortWeather/ShortWeather/Presentation/Common/Base/ViewController/BaseViewController.swift
  ShortWeather/ShortWeather/Presentation/Common/SideMenu/Cell/MenuTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/Common/SideMenu/ReusableView/MenuLineHeaderView.swift
  ShortWeather/ShortWeather/Presentation/Common/SideMenu/View/SideMenuView.swift
  ShortWeather/ShortWeather/Presentation/Common/Splash/SplashViewController.swift
  ShortWeather/ShortWeather/Presentation/Info/FirstInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/Main/Cell/TodayWeatherCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/Main/View/FirstTodayWeatherView.swift
  ShortWeather/ShortWeather/Presentation/Main/View/testSecondWeatherView.swift
  ShortWeather/ShortWeather/Presentation/Main/ViewController/TodayWeatherViewController.swift
  ShortWeather/ShortWeather/Util/Extension/UITableView +.swift
  ShortWeather/ShortWeather/Util/Extension/UIViewController +.swift
  ShortWeather/ShortWeather/Util/NameSpace/Letter.swift
Labels: Feat, 🐱서린

#15 [Design] 오늘 날씨2 뷰 구현
  ShortWeather/ShortWeather/Presentation/Info/FirstInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
Labels: Design, 🐰민

#16 [Rename] #5 - UIButton Extension 파일명 수정
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Util/Extension/UIButton +.swift
Labels: Rename, 🐰민

#20 Feature/#7 - 시간 출력 테스트
  ShortWeather/ShortWeather/Presentation/Info/ViewController/SecondInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/Info/ViewController/TimeViewController.swift
  ShortWeather/ShortWeather/Util/NameSpace/Letter.swift
Labels: Design, 🐸정

#24 Feature/#7 - 레이아웃 수정
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Presentation/Info/Cell/ListTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/Info/Cell/SelectCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/Info/ViewController/FirstInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/Info/ViewController/ListViewController.swift
  ShortWeather/ShortWeather/Presentation/Info/ViewController/SecondInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/Info/ViewController/TimeViewController.swift
  ShortWeather/ShortWeather/Presentation/Setting/Cell/SetSelectCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/Setting/ViewController/CommuteTimeViewController.swift
  ShortWeather/ShortWeather/Util/CustomClass/CheckButton.swift
Labels: Design, 🐸정

#25 [Design] #7 - CheckButton CustomClass 구현
  ShortWeather/ShortWeather/Util/CustomClass/CheckButton.swift
Labels: Design, 🐸정

#32 [Design] #31 - 오늘 날씨2 시간대별 날씨 뷰 수정
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
Labels: Design, 🐰민

#33 [Design] #17 - 설정 뷰 수정
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/Cell/AlarmTableViewCell.swift
Labels: Design, 🐰민

#41 [Feat] #38 - Letter 추가
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/Cell/AlarmTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/AlarmSettingViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/CommuteTimeViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/SettingViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/WakeUpTimeViewController.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/CommuteTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
  ShortWeather/ShortWeather/Util/NameSpace/Letter.swift
Labels: Feat, 🐰민

#43 [Fix] #42 - 오전/오후 변경
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Common/ViewController/TimeInfoViewController.swift
Labels: Fix, 🐸정

#45 [Fix] #40 - 정보 입력 폼 UIPicker 수정
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Common/ViewController/SettingBaseViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Common/ViewController/TimeInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Info/ViewController/FirstInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Info/ViewController/SecondInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/CommuteTimeViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Setting/ViewController/WakeUpTimeViewController.swift
  ShortWeather/ShortWeather/Util/CustomClass/DatePicker.swift
  ShortWeather/ShortWeather/Util/CustomClass/DatePickerTest.swift
  ShortWeather/ShortWeather/Util/CustomClass/SpecifyTime.swift
Labels: Fix, 🐸정

#49 [Feat] #37 - 오늘날씨2 모델 구현
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Data/Model/SecondTodayWeatherData.swift
  ShortWeather/ShortWeather/Data/Model/TimezonePrecipitationData.swift
  ShortWeather/ShortWeather/Data/Model/TimezoneWeatherData.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/CollectionViewCell/HourCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/CommuteTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
Labels: Feat, 🐰민

#52 [Feat] #37 - 오늘 날씨2 모델
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Data/Model/SecondTodayWeatherData.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/CollectionViewCell/HourCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/CommuteTableViewCell.swift
  ShortWeather/ShortWeather/Util/Extension/String +.swift
Labels: Feat, 🐰민

#59 [Feat] #50 - 정보입력 뷰 서버통신 완룡!
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Application/SceneDelegate.swift
  ShortWeather/ShortWeather/Data/DTO/ .gitkeep
  ShortWeather/ShortWeather/Data/DTO/User/CheckUserResponse.swift
  ShortWeather/ShortWeather/Data/DTO/User/PostUserRequest.swift
  ShortWeather/ShortWeather/Data/DTO/User/PostUserResponse.swift
  ShortWeather/ShortWeather/Data/Model/User.swift
  ShortWeather/ShortWeather/Network/APIService/Main/MainService.swift
  ShortWeather/ShortWeather/Network/APIService/User/UserAPI.swift
  ShortWeather/ShortWeather/Network/APIService/User/UserService.swift
  ShortWeather/ShortWeather/Network/Foundation/APIConst.swift
  ShortWeather/ShortWeather/Network/Foundation/URLConst.swift
  ShortWeather/ShortWeather/Presentation/Common/Splash/SplashViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Info/ViewController/FirstInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Info/ViewController/SecondInfoViewController.swift
  ShortWeather/ShortWeather/Util/Extension/Encodable +.swift
  ShortWeather/ShortWeather/Util/Extension/String +.swift
  ShortWeather/ShortWeather/Util/NameSpace/Letter.swift
Labels: Feat, 🐱서린

#68 [Fix] #65 - 날씨 이미지명 수정
  ShortWeather/ShortWeather/Data/Model/TimezoneWeatherData.swift
Labels: Fix, 🐰민

#76 [Fix] #65 - 오늘 날씨2 뷰 코드 수정 및 삭제
  ShortWeather/ShortWeather.xcodeproj/project.pbxproj
  ShortWeather/ShortWeather/Data/DTO/TodayWeatherDetail/DetailRainResponse.swift
  ShortWeather/ShortWeather/Data/DTO/TodayWeatherDetail/DetailTempRespone.swift
  ShortWeather/ShortWeather/Data/DTO/TodayWeatherDetail/DetailWeatherResponse.swift
  ShortWeather/ShortWeather/Data/Model/DetailRain.swift
  ShortWeather/ShortWeather/Data/Model/DetailTemp.swift
  ShortWeather/ShortWeather/Data/Model/SecondTodayWeather.swift
  ShortWeather/ShortWeather/Data/Model/TimezonePrecipitationData.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/CollectionViewCell/HourCollectionViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/CommuteTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/WeekWeather/Cell/WeekWeatherCollectionViewCell.swift
Labels: Fix, 🐰민

#77 [Rename] #67 - 변수/파일명 수정 + DTO 폴더 나누기
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TimeTableViewCell.swift
  ShortWeather/ShortWeather/Presentation/TodayWeather/Cell/TableViewCell/TodayTableViewCell.swift
Labels: Fix, 🐰민

#83 [Feat] #78 - TimeInfoViewController 시간 오류 수정
  ShortWeather/ShortWeather/Presentation/InfoSetting/Common/ViewController/SettingBaseViewController.swift
  ShortWeather/ShortWeather/Presentation/InfoSetting/Common/ViewController/TimeInfoViewController.swift
  ShortWeather/ShortWeather/Presentation/WeekWeather/Cell/WeekWeatherCollectionViewCell.swift
Labels: Fix, 🐸정

#87 [Fix] #84 - 주간날씨 레이아웃 진짜 수정 완룡
  ShortWeather/ShortWeather/Presentation/WeekWeather/Cell/WeekWeatherCollectionViewCell.swift
Labels: Fix, 🐸정
